export { default as get_involved_1 } from "./get-involved_1.png"
export { default as get_involved_2 } from "./get-involved_2.png"
export { default as get_involved_3 } from "./get-involved_3.png"
export { default as page_tear } from "./page-tear.svg"
export { default as page_tear_bottom } from "./page-tear-bottom.svg"