export { default as get_involved_1 } from "./get-involved_1.png"
export { default as get_involved_2 } from "./get-involved_2.png"
export { default as get_involved_3 } from "./get-involved_3.png"

export { default as page_tear } from "./page-tear.svg"
export { default as page_tear_bottom } from "./page-tear-bottom.svg"

export { default as our_initiatives_1} from "./our-initiatives_1.png"
export { default as our_initiatives_2} from "./our-initiatives_2.png"
export { default as our_initiatives_3} from "./our-initiatives_3.png"
export { default as our_initiatives_4} from "./our-initiatives_4.png"
export { default as our_initiatives_5} from "./our-initiatives_5.png"
export { default as our_initiatives_6} from "./our-initiatives_6.png"
export { default as our_initiatives_7} from "./our-initiatives_7.png"

export { default as focus_area_1} from "./focus_area-1.png"
export { default as focus_area_2} from "./focus_area-2.png"
export { default as focus_area_3} from "./focus_area-3.png"
export { default as focus_area_4} from "./focus_area-4.png"
export { default as focus_area_5} from "./focus_area-5.png"
export { default as focus_area_6} from "./focus_area-6.png"

export { default as slide_1} from "./slides/slide-bg_1.png"
export { default as slide_2} from "./slides/slide-bg_2.png"
export { default as slide_3} from "./slides/slide-bg_3.png"
export { default as slide_4} from "./slides/slide-bg_4.png"
export { default as slide_5} from "./slides/slide-bg_5.png"