export { default as cleanwater} from "./cleanwater.png"
export { default as life_below_water} from "./climate action-1.png"
export { default as parntership} from "./climate action-2.png"
export { default as climate_action} from "./climate action.png"
export { default as no_poverty} from "./no poverty.png"
export { default as zero_hunger} from "./zero hunger.png"