export { default as nova1} from "./nova-1.png"
export { default as nova2} from "./nova-2.png"
export { default as nova3} from "./nova-3.png"
export { default as nova4} from "./nova-4.png"
export { default as nova5} from "./nova-5.png"
export { default as nova6} from "./nova-6.png"